version: 0.0
os: linux

files:
  # 폴더 안의 모든 파일을 대상 디렉터리로 복사
  - source: /
    destination: /home/ec2-user/wealist/

permissions:
  - object: /home/ec2-user/wealist/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: board-service/deploy.script/deploy-cleanup.sh
      timeout: 600
      runas: ec2-user

  ApplicationStart:
    - location: board-service/deploy.script/deploy-app-start.sh
      timeout: 600
      runas: ec2-user

  ValidateService:
    - location: board-service/deploy.script/deploy-health-check.sh
      timeout: 300
      runas: ec2-user
